### ISSUE TITLE
Question regarding cloudfront

### ISSUE THREAD

**Issue by robertd** [JakePartusch/serverlessui#23]
Howdy. I’d really like to give this a try in the near future. Any plans on migrating away from `CloudFrontWebDistribution` to `Distribution`? New cloudfront implementation uses OAI under the hood and bucket doesn’t need to be public anymore. Thanks!

**Comment by JakePartusch** [comment]
Hey @robertd, thanks for the question! I _do_ think that I should migrate this to use `Distribution` rather than `CloudFrontWebDistribution`, thanks for pointing that out. Unfortunately, I don't think that Origin Access Identity will work for most website use-cases. As far as I understand, I don't think it is possible to configure an S3 bucket as a website _and_ use OAI?

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html

**Comment by robertd** [comment]
Yeah, It’s possible to serve websites with OAI powered setup. We’ve been using this setup at work. The fact that one can serve websites using so many different implementation patterns is somewhat confusing... I wish AWS identified the preferred best practice implementation 😄

Again, I’m not saying that you necessarily need to change your implementation I just wanted to hear your opinion on it and whether you’ve considered it or not.  👍

https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-serve-static-website/

**Comment by JakePartusch** [comment]
Great points. Yeah, I've used OAI with Nuxt, but to get nested routing to work, I had to write an additional Lambda Edge function (since S3 couldn't be configured as a website). Maybe they've fixed some of those problems? I'll give it a try again to see if we can make it work in a "zero-config" way.
